!!python/object:__main__.Configuration
repositoryUrl: "https://github.com/eclipse/rt.equinox.bundles"
repositoryShortname: "eclipse/rt.equinox.bundles"
repositoryPath: 'D:\Repos\rt.equinox.bundles'
analysisOutputPath: 'D:\Repos\analysisOutput\eclipse-rt.equinox.bundles'
aliasPath: 'D:\Repos\analysisOutput\aliases\eclipse-rt.equinox.bundles.yml'
aliasSimilarityMaxDistance: 0.25