!!python/object:__main__.Configuration
repositoryUrl: "https://github.com/eclipse-cdt/cdt"
repositoryShortname: "eclipse-cdt/cdt"
repositoryPath: 'D:\Repos\cdt'
analysisOutputPath: 'D:\Repos\analysisOutput'
aliasPath: 'D:\Repos\DevNetworkPython\aliases\eclipsecdt.yml'
aliasSimilarityMaxDistance: 0.25
