!!python/object:__main__.Configuration
repositoryUrl: "https://github.com/dotnet/core"
repositoryShortname: "dotnet/core"
repositoryPath: 'C:\repos\dotnet.core'
analysisOutputPath: 'C:\repos\analysisOutput\dotnet.core'
aliasPath: 'C:\repos\analysisOutput\aliases\dotnet.core.yml'
aliasSimilarityMaxDistance: 0.25