!!python/object:__main__.Configuration
repositoryUrl: "https://github.com/apache/gora"
repositoryShortname: "apache/gora"
repositoryPath: 'D:\Repos\apachegora'
analysisOutputPath: 'D:\Repos\analysisOutput'
aliasPath: 'D:\Repos\DevNetworkPython\aliases\apachegora.yml'
aliasSimilarityMaxDistance: 0.25
