!!python/object:__main__.Configuration
repositoryUrl: 'https://github.com/apache/mahout'
repositoryPath: 'D:\repos\apachemahout'
analysisOutputPath: 'D:\repos\analysisOutput'
aliasPath: 'D:\repos\DevNetworkPython\aliases\apachemahout.yml'