!!python/object:__main__.Configuration
repositoryUrl: 'https://github.com/apache/mahout'
repositoryPath: 'C:\Users\denio\source\repos\apachemahout'
analysisOutputPath: 'C:\Users\denio\source\repos\analysisOutput'
aliasPath: 'C:\Users\denio\source\repos\DevNetworkPython\aliases\apachemahout.yml'